### ISSUE TITLE
Cmd error/module error.

### ISSUE THREAD

**Issue by GhostShot3** [LegitSoulja/OgarConsole#11]
module.js:327
    throw err;
    ^

Error: Cannot find module './core/ControlServer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\PEDRO\Desktop\Todas as pasta\Ogar-unlimited-
master\src\plugins\OgarConsole-master\OgarUnlimitedLatest\index.js:5:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

C:\Users\PEDRO\Desktop\Todas as pasta\Ogar-unlimited-master\src\plugins\OgarCons
ole-master\OgarUnlimitedLatest>pause

**Comment by LegitSoulja** [comment]
Failed to update im guessing? Redownload ogarul, and upload all the files from ./core to core
